name = "icabbi-trips"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# Set WEBHOOK_SECRET via `wrangler secret put WEBHOOK_SECRET`
# Set FIREBASE_API_KEY via `wrangler secret put FIREBASE_API_KEY`
# Value: AIzaSyCaypEoug2f7OTJjKOdkkJPaZDypcr3NF8
FIREBASE_PROJECT_ID = "sms-dlx"
SUPABASE_URL = "https://mdutrtmdjodabggirntb.supabase.co"

# Set SUPABASE_SERVICE_KEY via `wrangler secret put SUPABASE_SERVICE_KEY`
